### ISSUE TITLE
env has no attribute 'sys'

### ISSUE THREAD

**Issue by KehanLong** [LeCAR-Lab/model-based-diffusion#2]
Thank you for open-sourcing the work! 

I am trying to visualize the diffusion process by running the commands: `python visualize_mbd.py --env_name $ENV_NAME`

However, I got the error of `AttributeError: 'Car2d' object has no attribute 'sys'`. 

I checked the car2d.py and it seems the sys is not defined in the Car2d class. Could you help with it? 

Besides, I think the file for visualization has been renamed to 'vis_diffusion.py', you may also need to update it in the readme.

**Comment by jc-bao** [comment]
Thank you so much for the feedback! I have updated the readme. For Car2D, since the environment is handwritten so it does not support Brax visualizer. If you want to visualize, PR are welcomed!
