### ISSUE TITLE
No self-collision in dynamics function?

### ISSUE THREAD

**Issue by liyitang22** [LeCAR-Lab/model-based-diffusion#3]
when running humanoidstandup task, it can generate some weird sequence like:

Uploading standup.mp4…

It looks like there is no self-collision in dynamics function?

**Comment by liyitang22** [comment]
https://github.com/user-attachments/assets/d27d5b2f-4de9-454a-94a0-921c668ae727

**Comment by jc-bao** [comment]
that's right. we ported it from `brax` and seems like they disable self-collision for the sake of speed. Feel free to add it back!
