### ISSUE TITLE
I fail to see the difference with MPPI?

### ISSUE THREAD

**Issue by JTaets** [LeCAR-Lab/model-based-diffusion#4]
Hi, I'm not quite sure that I understand your paper. Could you help me to understand the difference with MPPI?

As far as I can see, substituting  line 5 in line 6 givest $Y^{(i-1)} = \sqrt{\overline\alpha_{i-1}}  \overline{Y}^{(0)}$.
Substituting that in the sampling of the next loop (line 3) gives: $N(\overline{Y}^{(0)}, (\frac{1}{\overline\alpha_{i-1}}-1)I)$.
As far as I can see, the distribution above and line 4 are exactly like MPPI with scheduled noise. And I feel to see why this would be preferred over MPPI with noise scheduled using more principled methods like in https://ieeexplore.ieee.org/abstract/document/7487277

![image](https://github.com/user-attachments/assets/4c234d5b-11b4-451e-8c0a-13e26505a327)

**Comment by jc-bao** [comment]
@JTaets That's a quite insightful observation!

> **"As far as I can see, the distribution above and line 4 are exactly like MPPI with scheduled noise."**

You’re absolutely correct! We also mention this connection in our paper. For a detailed explanation of the relationship between our method and MPPI, I recommend reviewing the "Connection with Sampling-based Optimization" section in our *Model-based Diffusion* paper ([arxiv link](https://arxiv.org/pdf/2407.01573)) and the "Annealing in Diffusion Process" section in our *DIAL-MPC* paper ([arxiv link](https://arxiv.org/abs/2409.15610)). 

In summary, if you apply our *Model-based Diffusion* to deterministic dynamics, it indeed simplifies to MPPI but with varying noise levels. One of the key contributions of our work is revealing this connection and introducing an iterative refinement process into sampling-based MPC methods.

> **"And I fail to see why this would be preferred over MPPI with noise scheduled using more principled methods."**

The main distinction lies in how the noise scheduling is handled. In MBD, we follow a pre-scheduled forward corruption process, while in MPPI, the covariance is updated dynamically based on the sampled cost function. Whether one method is superior to the other is still an open question that requires further theoretical investigation. It's worth noting that there isn’t a general convergence analysis for MPPI yet, though some linear cases have been examined in our earlier work ([CoVO-MPC paper](https://lecar-lab.github.io/CoVO-MPC/)).

That said, empirical results suggest that the iterative refinement process in MBD enhances convergence performance. This is why we not only compare our approach with MPPI, but also with other optimization methods like CEM and CMA-ES. However, deeper theoretical comparisons between these approaches remain an area for future research.
